pwan_runtime_sources = files(
  'w2u_pwan_scratch.cpp',
  'w2u_pwan_archive.cpp',
  'w2u_summary_anim.cpp',
  'w2u_battle_anim.cpp',
  'w2u_nonbattle_mcss.cpp',
  'w2u_egg_hatch_anim.cpp',
  'w2u_evolution_anim.cpp',
  'w2u_resident_anchor.s',
  'w2u_summary_hooks.s',
  'w2u_battle_hooks.s',
  'w2u_nonbattle_hooks.s',
)

pwan_runtime_depend_files = files(
  'pwan_types.h',
  'w2u_pwan_archive.h',
  'w2u_pwan_config.h',
) + files(
  '../../include/stdint.h',
  '../../include/swan/swantypes.h',
  '../../include/swan/nds/fs.h',
)
