pokeweb_gameplay = files(
    'w2u_abilities.cpp',
    'w2u_ability_storage.cpp',
    'w2u_battle_module_loader.cpp',
    'w2u_field_effects.cpp',
    'w2u_items.cpp',
    'w2u_mega.cpp',
    'w2u_moves.cpp',
    'w2u_strong_weather.cpp',
    'w2u_terrain_indicator.cpp',
    'w2u_terrain_texture.cpp',
    'megab2w2/mb_resident.cpp',
    'w2u_mega_hooks.s',
    'w2u_move_animation_hooks.s',
    'w2u_transform_hooks.s',
    'w2u_damage_hooks.s',
    'w2u_terrain_indicator_hooks.s',
    'w2u_terrain_texture_hooks.s',
)

pokeweb_field = files(
    'w2u_field_items.cpp',
    'w2u_field_item_hooks.s',
)

pokeweb_ui = files(
    'w2u_ability_storage_ui.cpp',
    'w2u_mega_summary_hooks.s',
)

subdir('battle_modules')
